REM dotnet build 5-0\hello-world

dotnet build anonymous-id
dotnet build application-environment
dotnet build basic\hello-world
dotnet build basic\hello-world-2
dotnet build basic\hello-world-3
dotnet build basic\i-host-environment
dotnet build basic\i-webhost-environment
dotnet build basic\iconfiguration
dotnet build bedrock\echo\client
dotnet build bedrock\echo\server

cd blazor\
call build.bat
cd ..

cd blazor-ss\
call build.bat
cd ..

dotnet build caching\caching-1
dotnet build caching\caching-2
dotnet build caching\caching-3
dotnet build caching\caching-4
dotnet build caching\redis-cache
dotnet build configurations\configuration-1
dotnet build configurations\configuration-environment-variables
dotnet build configurations\configuration-ini
dotnet build configurations\configuration-ini-options
dotnet build configurations\configuration-options
dotnet build configurations\configuration-xml
dotnet build configurations\configuration-xml-options
dotnet build connection-info
dotnet build dependency-injection\dependency-injection-1
dotnet build dependency-injection\dependency-injection-3
dotnet build device-detection
dotnet build diagnostics\diagnostics-1
dotnet build diagnostics\diagnostics-2
dotnet build diagnostics\diagnostics-3
dotnet build diagnostics\diagnostics-4
dotnet build diagnostics\diagnostics-5
dotnet build diagnostics\diagnostics-6
dotnet build endpoint-routing\endpoint-routing
dotnet build endpoint-routing\endpoint-routing-2
dotnet build endpoint-routing\endpoint-routing-3
dotnet build endpoint-routing\endpoint-routing-4
REM dotnet build endpoint-routing\endpoint-routing-5
dotnet build endpoint-routing\endpoint-routing-6
dotnet build endpoint-routing\new-routing
dotnet build endpoint-routing\new-routing-10
dotnet build endpoint-routing\new-routing-11
dotnet build endpoint-routing\new-routing-12
dotnet build endpoint-routing\new-routing-13
dotnet build endpoint-routing\new-routing-14
dotnet build endpoint-routing\new-routing-15
dotnet build endpoint-routing\new-routing-16
dotnet build endpoint-routing\new-routing-17
dotnet build endpoint-routing\new-routing-18
dotnet build endpoint-routing\new-routing-19
dotnet build endpoint-routing\new-routing-2
dotnet build endpoint-routing\new-routing-20
dotnet build endpoint-routing\new-routing-21
dotnet build endpoint-routing\new-routing-22
dotnet build endpoint-routing\new-routing-23
dotnet build endpoint-routing\new-routing-24
dotnet build endpoint-routing\new-routing-25
dotnet build endpoint-routing\new-routing-26
dotnet build endpoint-routing\new-routing-27
dotnet build endpoint-routing\new-routing-28
dotnet build endpoint-routing\new-routing-29
dotnet build endpoint-routing\new-routing-3
dotnet build endpoint-routing\new-routing-30
dotnet build endpoint-routing\new-routing-4
# Removed due to API changes
# dotnet build endpoint-routing\new-routing-5
dotnet build endpoint-routing\new-routing-6
dotnet build endpoint-routing\new-routing-7
dotnet build endpoint-routing\new-routing-8
dotnet build endpoint-routing\new-routing-9
dotnet build endpoint-routing\parameter-transformer
dotnet build features\features-connection
dotnet build features\features-http-body-response
dotnet build features\features-max-request-body-size
dotnet build features\features-request-culture
dotnet build features\features-server-addresses
dotnet build features\features-server-addresses-2
dotnet build features\features-server-custom
dotnet build features\features-server-custom-override
dotnet build features\features-server-request
dotnet build features\features-session
dotnet build features\features-session-redis-2
dotnet build file-provider\file-provider-custom
dotnet build file-provider\file-provider-physical
dotnet build file-provider\serve-static-files-1
dotnet build file-provider\serve-static-files-2
dotnet build file-provider\serve-static-files-3
dotnet build file-provider\serve-static-files-4
dotnet build file-provider\serve-static-files-5
dotnet build file-provider\serve-static-files-6
dotnet build generic-host\generic-host-1
dotnet build generic-host\generic-host-2
dotnet build generic-host\generic-host-3
dotnet build generic-host\generic-host-4
dotnet build generic-host\generic-host-5
dotnet build generic-host\generic-host-configure-app
dotnet build generic-host\generic-host-configure-host
dotnet build generic-host\generic-host-configure-logging
dotnet build generic-host\generic-host-environment
dotnet build generic-host\generic-host-ihostapplicationlifetime
dotnet build grpc\grpc\client
dotnet build grpc\grpc\server
dotnet build grpc\grpc-10\client
dotnet build grpc\grpc-10\server
dotnet build grpc\grpc-11\client
dotnet build grpc\grpc-11\server
dotnet build grpc\grpc-2\client
dotnet build grpc\grpc-2\server
dotnet build grpc\grpc-3\client
dotnet build grpc\grpc-3\server
dotnet build grpc\grpc-4\client
dotnet build grpc\grpc-4\server
dotnet build grpc\grpc-5\client
dotnet build grpc\grpc-5\server
dotnet build grpc\grpc-6\client
dotnet build grpc\grpc-6\server
dotnet build grpc\grpc-7\client
dotnet build grpc\grpc-7\server
dotnet build grpc\grpc-8\client
dotnet build grpc\grpc-8\server
dotnet build grpc\grpc-9\client
dotnet build grpc\grpc-9\server
dotnet build health-check\health-check-1
dotnet build health-check\health-check-2
dotnet build health-check\health-check-3
dotnet build health-check\health-check-4
dotnet build health-check\health-check-5
dotnet build health-check\health-check-6
dotnet build http-status-codes
dotnet build httpclientfactory\httpclientfactory-1
dotnet build httpclientfactory\httpclientfactory-2
dotnet build httpclientfactory\httpclientfactory-3
dotnet build httpclientfactory\httpclientfactory-4
dotnet build i-application-lifetime
dotnet build ihosted-service\ihosted-service-1
dotnet build image-sharp
dotnet build json\json
dotnet build json\json-2
dotnet build json\json-3
dotnet build json\json-4
dotnet build json\json-5
dotnet build json\json-6
dotnet build json\json-7
dotnet build json\json-8
dotnet build json\json-9
dotnet build json\json-10
dotnet build json\json-11

dotnet build localization\localization-1
dotnet build localization\localization-2
dotnet build localization\localization-3
dotnet build localization\localization-4
dotnet build localization\localization-5
dotnet build localization\localization-6
dotnet build logging\logging-1
dotnet build logging\logging-2
dotnet build mailkit\mailkit-1
dotnet build mailkit\mailkit-2
dotnet build markdown-server
dotnet build markdown-server-middleware
dotnet build media-type-names
dotnet build media-type-names-2
dotnet build middleware\middleware-0
dotnet build middleware\middleware-1
dotnet build middleware\middleware-10
dotnet build middleware\middleware-11
dotnet build middleware\middleware-12
dotnet build middleware\middleware-13
dotnet build middleware\middleware-2
dotnet build middleware\middleware-3
dotnet build middleware\middleware-4
dotnet build middleware\middleware-5
dotnet build middleware\middleware-6
dotnet build middleware\middleware-7
dotnet build middleware\middleware-8
dotnet build middleware\middleware-9
dotnet build mvc\api-problem-details
dotnet build mvc\api-problem-details-2
dotnet build mvc\api-versioning
dotnet build mvc\hello-world
dotnet build mvc\jwt
dotnet build mvc\localization\mvc-localization-1
dotnet build mvc\localization\mvc-localization-2
dotnet build mvc\localization\mvc-localization-3
dotnet build mvc\localization\mvc-localization-4
dotnet build mvc\localization\mvc-localization-5
dotnet build mvc\localization\mvc-localization-6
dotnet build mvc\localization\mvc-localization-7\src\ProjectWithResources
dotnet build mvc\localization\mvc-localization-7\src\Web
dotnet build mvc\localization\mvc-localization-8
dotnet build mvc\localization\mvc-localization-9
dotnet build mvc\model-binding-from-query
dotnet build mvc\model-binding-from-route
dotnet build mvc\mvc-output-xml
dotnet build mvc\nswag
dotnet build mvc\nswag-2
dotnet build mvc\output-formatter-syndication
REM dotnet build mvc\razor-class-library\razor-class-library-1\src\RazorClassLibrary1
REM dotnet build mvc\razor-class-library\razor-class-library-1\src\RazorClassLibrary2
REM dotnet build mvc\razor-class-library\razor-class-library-1\src\WebApplication
REM dotnet build mvc\razor-class-library\razor-class-library-with-controllers\src\RazorClassLibrary1
REM dotnet build mvc\razor-class-library\razor-class-library-with-controllers\src\WebApplication
REM dotnet build mvc\razor-class-library\razor-class-library-with-static-files\src\RazorClassLibrary1
REM dotnet build mvc\razor-class-library\razor-class-library-with-static-files\src\RazorClassLibrary2
REM dotnet build mvc\razor-class-library\razor-class-library-with-static-files\src\RazorClassLibraries.Mvc.Core
REM dotnet build mvc\razor-class-library\razor-class-library-with-static-files\src\WebApplication
dotnet build mvc\result-filestream
dotnet build mvc\result-physicalfile
dotnet build mvc\routing\routing-1
dotnet build mvc\routing\routing-2
dotnet build mvc\routing\routing-3
dotnet build mvc\routing\routing-4
dotnet build mvc\routing\routing-5
dotnet build mvc\routing\routing-6
dotnet build mvc\routing\routing-7
dotnet build mvc\routing\routing-8
dotnet build mvc\routing\routing-9
dotnet build mvc\tag-helper\tag-helper-1
dotnet build mvc\tag-helper\tag-helper-2
dotnet build mvc\tag-helper\tag-helper-3
dotnet build mvc\tag-helper\tag-helper-4
dotnet build mvc\tag-helper\tag-helper-5
dotnet build mvc\tag-helper\tag-helper-img
dotnet build mvc\tag-helper\tag-helper-link
dotnet build mvc\utf8json-formatter
dotnet build mvc\view-component\view-component-1
dotnet build mvc\view-component\view-component-2
dotnet build mvc\view-component\view-component-3
dotnet build mvc\view-component\view-component-4
dotnet build newtonsoft-json
dotnet build orchard-core\multi-tenant\Host
dotnet build orchard-core\routing\ForumModule
dotnet build orchard-core\routing\Host
dotnet build orchard-core\routing\TicketModule
dotnet build orchard-core\routing-2\ForumModule
dotnet build orchard-core\routing-2\Host
dotnet build orchard-core\routing-2\TicketModule
dotnet build orchard-core\static-files\ForumModule
dotnet build orchard-core\static-files\Host
dotnet build password-hasher
dotnet build razor-pages\custom-html-generator
dotnet build razor-pages\hello-world
dotnet build razor-pages\razor\razor-1
dotnet build razor-pages\razor\razor-2
dotnet build razor-pages\razor-pages-basic
dotnet build razor-pages\razor-pages-mvc
dotnet build razor-pages\routing
dotnet build razor-pages\routing-2
dotnet build request\anti-forgery
dotnet build request\cookies-1
dotnet build request\cookies-2
dotnet build request\form-upload-file
dotnet build request\form-values
dotnet build request\query-string-1
dotnet build request\query-string-2
dotnet build request\query-string-3
dotnet build request\request-headers
dotnet build request\request-headers-names
dotnet build request\request-headers-typed
dotnet build request\request-verb
dotnet build response\compression-response
dotnet build response\response-buffering
dotnet build response\response-header
dotnet build response\trailing-headers
dotnet build rewrite\rewrite-1
dotnet build rewrite\rewrite-2
dotnet build rewrite\rewrite-3
dotnet build rewrite\rewrite-4
dotnet build rewrite\rewrite-5
dotnet build rewrite\rewrite-6
dotnet build security\authentication-with-identity\src
dotnet build signalr\signalr-1\Client
dotnet build signalr\signalr-1\Server
dotnet build sse
dotnet build startup\env-development
dotnet build startup\no-startup
dotnet build startup\startup-basic
dotnet build startup\startup-basic-multiple
dotnet build startup\startup-basic-multiple-environment
dotnet build startup\startup-basic-multiple-urls
dotnet build startup\startup-capture-errors
dotnet build startup\startup-custom-name
dotnet build startup\startup-istartupfilter
dotnet build startup\startup-multiple-configure-environment
dotnet build startup\startup-multiple-configure-environment-services
dotnet build startup\suppress-status-messages
dotnet build syndications\syndication-1
dotnet build syndications\syndication-2
dotnet build syndications\syndication-3
dotnet build uri-helper\uri-helper-build-absolute
dotnet build uri-helper\uri-helper-from-absolute
dotnet build uri-helper\uri-helper-get-display-url
dotnet build uri-helper\uri-helper-get-encoded-path-and-query
dotnet build uri-helper\uri-helper-get-encoded-url
dotnet build version
dotnet build web-sockets\web-sockets-1
dotnet build web-sockets\web-sockets-2
dotnet build web-sockets\web-sockets-3
dotnet build web-sockets\web-sockets-4
dotnet build web-sockets\web-sockets-5
dotnet build web-utilities\web-utilities-query-helpers
dotnet build web-utilities\web-utilities-query-helpers-2
dotnet build web-utilities\web-utilities-reason-phrases

dotnet build sfa\wiki

dotnet build orleans\hello-world\client\
dotnet build orleans\hello-world\silo\
dotnet build orleans\hello-world-2\client
dotnet build orleans\hello-world-2\silo
dotnet build orleans\hello-world-3
dotnet build orleans\hello-world-4
dotnet build orleans\http-client
dotnet build orleans\reminder
dotnet build orleans\rss-reader
dotnet build orleans\rss-reader-2
dotnet build orleans\rss-reader-3
dotnet build orleans\rss-reader-4
dotnet build orleans\rss-reader-5
dotnet build orleans\rss-reader-6
dotnet build orleans\timer

