REM dotnet clean 5-0\hello-world

dotnet clean anonymous-id
dotnet clean application-environment
dotnet clean basic\hello-world
dotnet clean basic\hello-world-2
dotnet clean basic\i-host-environment
dotnet clean basic\i-webhost-environment
dotnet clean basic\iconfiguration
dotnet clean bedrock\echo\client
dotnet clean bedrock\echo\server
dotnet clean blazor\Component
dotnet clean blazor\ComponentEight
dotnet clean blazor\ComponentEleven
dotnet clean blazor\ComponentFifteen
dotnet clean blazor\ComponentFive
dotnet clean blazor\ComponentFour
dotnet clean blazor\ComponentFourteen
dotnet clean blazor\ComponentNine
dotnet clean blazor\ComponentSeven
dotnet clean blazor\ComponentSix
dotnet clean blazor\ComponentTen
dotnet clean blazor\ComponentThirteen
dotnet clean blazor\ComponentThree
dotnet clean blazor\ComponentTwelve
dotnet clean blazor\ComponentTwo
dotnet clean blazor\DataBinding
dotnet clean blazor\DataBindingTwo
dotnet clean blazor\HelloWorld
dotnet clean blazor-ss\ChatR
dotnet clean blazor-ss\Chatter
dotnet clean blazor-ss\DependencyInjection
dotnet clean blazor-ss\HelloWorld
dotnet clean blazor-ss\JsIntegration
dotnet clean blazor-ss\Layout
dotnet clean blazor-ss\MultiApps\App1
dotnet clean blazor-ss\MultiApps\App2
dotnet clean blazor-ss\MultiApps\AppHost
dotnet clean blazor-ss\RssReader
dotnet clean blazor-ss\RssReader-2
dotnet clean blazor-ss\StartingVariation
dotnet clean caching\caching-1
dotnet clean caching\caching-2
dotnet clean caching\caching-3
dotnet clean caching\caching-4
dotnet clean caching\redis-cache
dotnet clean configurations\configuration-1
dotnet clean configurations\configuration-environment-variables
dotnet clean configurations\configuration-ini
dotnet clean configurations\configuration-ini-options
dotnet clean configurations\configuration-options
dotnet clean configurations\configuration-xml
dotnet clean configurations\configuration-xml-options
dotnet clean connection-info
dotnet clean dependency-injection\dependency-injection-1
dotnet clean dependency-injection\dependency-injection-3
dotnet clean device-detection
dotnet clean diagnostics\diagnostics-1
dotnet clean diagnostics\diagnostics-2
dotnet clean diagnostics\diagnostics-3
dotnet clean diagnostics\diagnostics-4
dotnet clean diagnostics\diagnostics-5
dotnet clean diagnostics\diagnostics-6
dotnet clean endpoint-routing\endpoint-routing
dotnet clean endpoint-routing\endpoint-routing-2
dotnet clean endpoint-routing\endpoint-routing-3
dotnet clean endpoint-routing\endpoint-routing-4
dotnet clean endpoint-routing\endpoint-routing-5
dotnet clean endpoint-routing\endpoint-routing-6
dotnet clean endpoint-routing\new-routing
dotnet clean endpoint-routing\new-routing-10
dotnet clean endpoint-routing\new-routing-11
dotnet clean endpoint-routing\new-routing-12
dotnet clean endpoint-routing\new-routing-13
dotnet clean endpoint-routing\new-routing-14
dotnet clean endpoint-routing\new-routing-15
dotnet clean endpoint-routing\new-routing-16
dotnet clean endpoint-routing\new-routing-17
dotnet clean endpoint-routing\new-routing-18
dotnet clean endpoint-routing\new-routing-19
dotnet clean endpoint-routing\new-routing-2
dotnet clean endpoint-routing\new-routing-20
dotnet clean endpoint-routing\new-routing-21
dotnet clean endpoint-routing\new-routing-22
dotnet clean endpoint-routing\new-routing-23
dotnet clean endpoint-routing\new-routing-24
dotnet clean endpoint-routing\new-routing-25
dotnet clean endpoint-routing\new-routing-26
dotnet clean endpoint-routing\new-routing-27
dotnet clean endpoint-routing\new-routing-28
dotnet clean endpoint-routing\new-routing-29
dotnet clean endpoint-routing\new-routing-3
dotnet clean endpoint-routing\new-routing-30
dotnet clean endpoint-routing\new-routing-4
dotnet clean endpoint-routing\new-routing-5
dotnet clean endpoint-routing\new-routing-6
dotnet clean endpoint-routing\new-routing-7
dotnet clean endpoint-routing\new-routing-8
dotnet clean endpoint-routing\new-routing-9
dotnet clean endpoint-routing\parameter-transformer
dotnet clean features\features-connection
dotnet clean features\features-http-body-response
dotnet clean features\features-max-request-body-size
dotnet clean features\features-request-culture
dotnet clean features\features-server-addresses
dotnet clean features\features-server-addresses-2
dotnet clean features\features-server-custom
dotnet clean features\features-server-custom-override
dotnet clean features\features-server-request
dotnet clean features\features-session
dotnet clean features\features-session-redis-2
dotnet clean file-provider\file-provider-custom
dotnet clean file-provider\file-provider-physical
dotnet clean file-provider\serve-static-files-1
dotnet clean file-provider\serve-static-files-2
dotnet clean file-provider\serve-static-files-3
dotnet clean file-provider\serve-static-files-4
dotnet clean file-provider\serve-static-files-5
dotnet clean file-provider\serve-static-files-6
dotnet clean generic-host\generic-host-1
dotnet clean generic-host\generic-host-2
dotnet clean generic-host\generic-host-3
dotnet clean generic-host\generic-host-4
dotnet clean generic-host\generic-host-5
dotnet clean generic-host\generic-host-configure-app
dotnet clean generic-host\generic-host-configure-host
dotnet clean generic-host\generic-host-configure-logging
dotnet clean generic-host\generic-host-environment
dotnet clean generic-host\generic-host-ihostapplicationlifetime
dotnet clean grpc\grpc\client
dotnet clean grpc\grpc\server
dotnet clean grpc\grpc-10\client
dotnet clean grpc\grpc-10\server
dotnet clean grpc\grpc-11\client
dotnet clean grpc\grpc-11\server
dotnet clean grpc\grpc-2\client
dotnet clean grpc\grpc-2\server
dotnet clean grpc\grpc-3\client
dotnet clean grpc\grpc-3\server
dotnet clean grpc\grpc-4\client
dotnet clean grpc\grpc-4\server
dotnet clean grpc\grpc-5\client
dotnet clean grpc\grpc-5\server
dotnet clean grpc\grpc-6\client
dotnet clean grpc\grpc-6\server
dotnet clean grpc\grpc-7\client
dotnet clean grpc\grpc-7\server
dotnet clean grpc\grpc-8\client
dotnet clean grpc\grpc-8\server
dotnet clean grpc\grpc-9\client
dotnet clean grpc\grpc-9\server
dotnet clean health-check\health-check-1
dotnet clean health-check\health-check-2
dotnet clean health-check\health-check-3
dotnet clean health-check\health-check-4
dotnet clean health-check\health-check-5
dotnet clean health-check\health-check-6
dotnet clean http-status-codes
dotnet clean httpclientfactory\httpclientfactory-1
dotnet clean httpclientfactory\httpclientfactory-2
dotnet clean httpclientfactory\httpclientfactory-3
dotnet clean httpclientfactory\httpclientfactory-4
dotnet clean i-application-lifetime
dotnet clean ihosted-service\ihosted-service-1
dotnet clean image-sharp
dotnet clean json\json
dotnet clean json\json-2
dotnet clean json\json-3
dotnet clean json\json-4
dotnet clean json\json-5
dotnet clean json\json-6
dotnet clean json\json-7
dotnet clean json\json-8
dotnet clean json\json-9
dotnet clean localization\localization-1
dotnet clean localization\localization-2
dotnet clean localization\localization-3
dotnet clean localization\localization-4
dotnet clean localization\localization-5
dotnet clean localization\localization-6
dotnet clean logging\logging-1
dotnet clean logging\logging-2
dotnet clean mailkit\mailkit-1
dotnet clean mailkit\mailkit-2
dotnet clean markdown-server
dotnet clean markdown-server-middleware
dotnet clean media-type-names
dotnet clean media-type-names-2
dotnet clean middleware\middleware-0
dotnet clean middleware\middleware-1
dotnet clean middleware\middleware-10
dotnet clean middleware\middleware-11
dotnet clean middleware\middleware-12
dotnet clean middleware\middleware-2
dotnet clean middleware\middleware-3
dotnet clean middleware\middleware-4
dotnet clean middleware\middleware-5
dotnet clean middleware\middleware-6
dotnet clean middleware\middleware-7
dotnet clean middleware\middleware-8
dotnet clean middleware\middleware-9
dotnet clean mvc\api-problem-details
dotnet clean mvc\api-problem-details-2
dotnet clean mvc\api-versioning
dotnet clean mvc\hello-world
dotnet clean mvc\jwt
dotnet clean mvc\localization\mvc-localization-1
dotnet clean mvc\localization\mvc-localization-2
dotnet clean mvc\localization\mvc-localization-3
dotnet clean mvc\localization\mvc-localization-4
dotnet clean mvc\localization\mvc-localization-5
dotnet clean mvc\localization\mvc-localization-6
dotnet clean mvc\localization\mvc-localization-7\src\ProjectWithResources
dotnet clean mvc\localization\mvc-localization-7\src\Web
dotnet clean mvc\localization\mvc-localization-8
dotnet clean mvc\localization\mvc-localization-9
dotnet clean mvc\model-binding-from-query
dotnet clean mvc\model-binding-from-route
dotnet clean mvc\mvc-output-xml
dotnet clean mvc\nswag
dotnet clean mvc\nswag-2
dotnet clean mvc\output-formatter-syndication
dotnet clean mvc\razor-class-library\razor-class-library-1\src\RazorClassLibrary1
dotnet clean mvc\razor-class-library\razor-class-library-1\src\RazorClassLibrary2
dotnet clean mvc\razor-class-library\razor-class-library-1\src\WebApplication
dotnet clean mvc\razor-class-library\razor-class-library-with-controllers\src\RazorClassLibrary1
dotnet clean mvc\razor-class-library\razor-class-library-with-controllers\src\WebApplication
dotnet clean mvc\razor-class-library\razor-class-library-with-static-files\src\RazorClassLibraries.Mvc.Core
dotnet clean mvc\razor-class-library\razor-class-library-with-static-files\src\RazorClassLibrary1
dotnet clean mvc\razor-class-library\razor-class-library-with-static-files\src\RazorClassLibrary2
dotnet clean mvc\razor-class-library\razor-class-library-with-static-files\src\WebApplication
dotnet clean mvc\result-filestream
dotnet clean mvc\result-physicalfile
dotnet clean mvc\routing\routing-1
dotnet clean mvc\routing\routing-2
dotnet clean mvc\routing\routing-3
dotnet clean mvc\routing\routing-4
dotnet clean mvc\routing\routing-5
dotnet clean mvc\routing\routing-6
dotnet clean mvc\routing\routing-7
dotnet clean mvc\routing\routing-8
dotnet clean mvc\routing\routing-9
dotnet clean mvc\tag-helper\tag-helper-1
dotnet clean mvc\tag-helper\tag-helper-2
dotnet clean mvc\tag-helper\tag-helper-3
dotnet clean mvc\tag-helper\tag-helper-4
dotnet clean mvc\tag-helper\tag-helper-5
dotnet clean mvc\tag-helper\tag-helper-img
dotnet clean mvc\tag-helper\tag-helper-link
dotnet clean mvc\utf8json-formatter
dotnet clean mvc\view-component\view-component-1
dotnet clean mvc\view-component\view-component-2
dotnet clean mvc\view-component\view-component-3
dotnet clean mvc\view-component\view-component-4
dotnet clean newtonsoft-json
dotnet clean orchard-core\multi-tenant\Host
dotnet clean orchard-core\routing\ForumModule
dotnet clean orchard-core\routing\Host
dotnet clean orchard-core\routing\TicketModule
dotnet clean orchard-core\routing-2\ForumModule
dotnet clean orchard-core\routing-2\Host
dotnet clean orchard-core\routing-2\TicketModule
dotnet clean orchard-core\static-files\ForumModule
dotnet clean orchard-core\static-files\Host
dotnet clean password-hasher
dotnet clean razor-pages\custom-html-generator
dotnet clean razor-pages\hello-world
dotnet clean razor-pages\razor\razor-1
dotnet clean razor-pages\razor\razor-2
dotnet clean razor-pages\razor-pages-basic
dotnet clean razor-pages\razor-pages-mvc
dotnet clean razor-pages\routing
dotnet clean razor-pages\routing-2
dotnet clean request\anti-forgery
dotnet clean request\cookies-1
dotnet clean request\cookies-2
dotnet clean request\form-upload-file
dotnet clean request\form-values
dotnet clean request\query-string-1
dotnet clean request\query-string-2
dotnet clean request\query-string-3
dotnet clean request\request-headers
dotnet clean request\request-headers-names
dotnet clean request\request-headers-typed
dotnet clean request\request-verb
dotnet clean response\compression-response
dotnet clean response\response-buffering
dotnet clean response\response-header
dotnet clean response\trailing-headers
dotnet clean rewrite\rewrite-1
dotnet clean rewrite\rewrite-2
dotnet clean rewrite\rewrite-3
dotnet clean rewrite\rewrite-4
dotnet clean rewrite\rewrite-5
dotnet clean rewrite\rewrite-6
dotnet clean security\authentication-with-identity\src
dotnet clean signalr\signalr-1\Client
dotnet clean signalr\signalr-1\Server
dotnet clean sse
dotnet clean startup\env-development
dotnet clean startup\no-startup
dotnet clean startup\startup-basic
dotnet clean startup\startup-basic-multiple
dotnet clean startup\startup-basic-multiple-environment
dotnet clean startup\startup-basic-multiple-urls
dotnet clean startup\startup-capture-errors
dotnet clean startup\startup-custom-name
dotnet clean startup\startup-istartupfilter
dotnet clean startup\startup-multiple-configure-environment
dotnet clean startup\startup-multiple-configure-environment-services
dotnet clean startup\suppress-status-messages
dotnet clean syndications\syndication-1
dotnet clean syndications\syndication-2
dotnet clean syndications\syndication-3
dotnet clean uri-helper\uri-helper-build-absolute
dotnet clean uri-helper\uri-helper-from-absolute
dotnet clean uri-helper\uri-helper-get-display-url
dotnet clean uri-helper\uri-helper-get-encoded-path-and-query
dotnet clean uri-helper\uri-helper-get-encoded-url
dotnet clean version
dotnet clean web-sockets\web-sockets-1
dotnet clean web-sockets\web-sockets-2
dotnet clean web-sockets\web-sockets-3
dotnet clean web-sockets\web-sockets-4
dotnet clean web-sockets\web-sockets-5
dotnet clean web-utilities\web-utilities-query-helpers
dotnet clean web-utilities\web-utilities-query-helpers-2
dotnet clean web-utilities\web-utilities-reason-phrases
