@REM dotnet restore 5-0\hello-world

dotnet restore anonymous-id
dotnet restore application-environment
dotnet restore basic\hello-world
dotnet restore basic\hello-world-2
dotnet restore basic\i-host-environment
dotnet restore basic\i-webhost-environment
dotnet restore basic\iconfiguration
dotnet restore bedrock\echo\client
dotnet restore bedrock\echo\server
dotnet restore blazor\Component
dotnet restore blazor\ComponentEight
dotnet restore blazor\ComponentEleven
dotnet restore blazor\ComponentFifteen
dotnet restore blazor\ComponentFive
dotnet restore blazor\ComponentFour
dotnet restore blazor\ComponentFourteen
dotnet restore blazor\ComponentNine
dotnet restore blazor\ComponentSeven
dotnet restore blazor\ComponentSix
dotnet restore blazor\ComponentTen
dotnet restore blazor\ComponentThirteen
dotnet restore blazor\ComponentThree
dotnet restore blazor\ComponentTwelve
dotnet restore blazor\ComponentTwo
dotnet restore blazor\DataBinding
dotnet restore blazor\DataBindingTwo
dotnet restore blazor\HelloWorld
dotnet restore blazor-ss\ChatR
dotnet restore blazor-ss\Chatter
dotnet restore blazor-ss\DependencyInjection
dotnet restore blazor-ss\HelloWorld
dotnet restore blazor-ss\JsIntegration
dotnet restore blazor-ss\Layout
dotnet restore blazor-ss\MultiApps\App1
dotnet restore blazor-ss\MultiApps\App2
dotnet restore blazor-ss\MultiApps\AppHost
dotnet restore blazor-ss\RssReader
dotnet restore blazor-ss\RssReader-2
dotnet restore blazor-ss\StartingVariation
dotnet restore caching\caching-1
dotnet restore caching\caching-2
dotnet restore caching\caching-3
dotnet restore caching\caching-4
dotnet restore caching\redis-cache
dotnet restore configurations\configuration-1
dotnet restore configurations\configuration-environment-variables
dotnet restore configurations\configuration-ini
dotnet restore configurations\configuration-ini-options
dotnet restore configurations\configuration-options
dotnet restore configurations\configuration-xml
dotnet restore configurations\configuration-xml-options
dotnet restore connection-info
dotnet restore dependency-injection\dependency-injection-1
dotnet restore dependency-injection\dependency-injection-3
dotnet restore device-detection
dotnet restore diagnostics\diagnostics-1
dotnet restore diagnostics\diagnostics-2
dotnet restore diagnostics\diagnostics-3
dotnet restore diagnostics\diagnostics-4
dotnet restore diagnostics\diagnostics-5
dotnet restore diagnostics\diagnostics-6
dotnet restore endpoint-routing\endpoint-routing
dotnet restore endpoint-routing\endpoint-routing-2
dotnet restore endpoint-routing\endpoint-routing-3
dotnet restore endpoint-routing\endpoint-routing-4
dotnet restore endpoint-routing\endpoint-routing-5
dotnet restore endpoint-routing\endpoint-routing-6
dotnet restore endpoint-routing\new-routing
dotnet restore endpoint-routing\new-routing-10
dotnet restore endpoint-routing\new-routing-11
dotnet restore endpoint-routing\new-routing-12
dotnet restore endpoint-routing\new-routing-13
dotnet restore endpoint-routing\new-routing-14
dotnet restore endpoint-routing\new-routing-15
dotnet restore endpoint-routing\new-routing-16
dotnet restore endpoint-routing\new-routing-17
dotnet restore endpoint-routing\new-routing-18
dotnet restore endpoint-routing\new-routing-19
dotnet restore endpoint-routing\new-routing-2
dotnet restore endpoint-routing\new-routing-20
dotnet restore endpoint-routing\new-routing-21
dotnet restore endpoint-routing\new-routing-22
dotnet restore endpoint-routing\new-routing-23
dotnet restore endpoint-routing\new-routing-24
dotnet restore endpoint-routing\new-routing-25
dotnet restore endpoint-routing\new-routing-26
dotnet restore endpoint-routing\new-routing-27
dotnet restore endpoint-routing\new-routing-28
dotnet restore endpoint-routing\new-routing-29
dotnet restore endpoint-routing\new-routing-3
dotnet restore endpoint-routing\new-routing-30
dotnet restore endpoint-routing\new-routing-4
dotnet restore endpoint-routing\new-routing-5
dotnet restore endpoint-routing\new-routing-6
dotnet restore endpoint-routing\new-routing-7
dotnet restore endpoint-routing\new-routing-8
dotnet restore endpoint-routing\new-routing-9
dotnet restore endpoint-routing\parameter-transformer
dotnet restore features\features-connection
dotnet restore features\features-http-body-response
dotnet restore features\features-max-request-body-size
dotnet restore features\features-request-culture
dotnet restore features\features-server-addresses
dotnet restore features\features-server-addresses-2
dotnet restore features\features-server-custom
dotnet restore features\features-server-custom-override
dotnet restore features\features-server-request
dotnet restore features\features-session
dotnet restore features\features-session-redis-2
dotnet restore file-provider\file-provider-custom
dotnet restore file-provider\file-provider-physical
dotnet restore file-provider\serve-static-files-1
dotnet restore file-provider\serve-static-files-2
dotnet restore file-provider\serve-static-files-3
dotnet restore file-provider\serve-static-files-4
dotnet restore file-provider\serve-static-files-5
dotnet restore file-provider\serve-static-files-6
dotnet restore generic-host\generic-host-1
dotnet restore generic-host\generic-host-2
dotnet restore generic-host\generic-host-3
dotnet restore generic-host\generic-host-4
dotnet restore generic-host\generic-host-5
dotnet restore generic-host\generic-host-configure-app
dotnet restore generic-host\generic-host-configure-host
dotnet restore generic-host\generic-host-configure-logging
dotnet restore generic-host\generic-host-environment
dotnet restore generic-host\generic-host-ihostapplicationlifetime
dotnet restore grpc\grpc\client
dotnet restore grpc\grpc\server
dotnet restore grpc\grpc-10\client
dotnet restore grpc\grpc-10\server
dotnet restore grpc\grpc-11\client
dotnet restore grpc\grpc-11\server
dotnet restore grpc\grpc-2\client
dotnet restore grpc\grpc-2\server
dotnet restore grpc\grpc-3\client
dotnet restore grpc\grpc-3\server
dotnet restore grpc\grpc-4\client
dotnet restore grpc\grpc-4\server
dotnet restore grpc\grpc-5\client
dotnet restore grpc\grpc-5\server
dotnet restore grpc\grpc-6\client
dotnet restore grpc\grpc-6\server
dotnet restore grpc\grpc-7\client
dotnet restore grpc\grpc-7\server
dotnet restore grpc\grpc-8\client
dotnet restore grpc\grpc-8\server
dotnet restore grpc\grpc-9\client
dotnet restore grpc\grpc-9\server
dotnet restore health-check\health-check-1
dotnet restore health-check\health-check-2
dotnet restore health-check\health-check-3
dotnet restore health-check\health-check-4
dotnet restore health-check\health-check-5
dotnet restore health-check\health-check-6
dotnet restore http-status-codes
dotnet restore httpclientfactory\httpclientfactory-1
dotnet restore httpclientfactory\httpclientfactory-2
dotnet restore httpclientfactory\httpclientfactory-3
dotnet restore httpclientfactory\httpclientfactory-4
dotnet restore i-application-lifetime
dotnet restore ihosted-service\ihosted-service-1
dotnet restore image-sharp
dotnet restore json\json
dotnet restore json\json-2
dotnet restore json\json-3
dotnet restore json\json-4
dotnet restore json\json-5
dotnet restore json\json-6
dotnet restore json\json-7
dotnet restore json\json-8
dotnet restore json\json-9
dotnet restore localization\localization-1
dotnet restore localization\localization-2
dotnet restore localization\localization-3
dotnet restore localization\localization-4
dotnet restore localization\localization-5
dotnet restore localization\localization-6
dotnet restore logging\logging-1
dotnet restore logging\logging-2
dotnet restore mailkit\mailkit-1
dotnet restore mailkit\mailkit-2
dotnet restore markdown-server
dotnet restore markdown-server-middleware
dotnet restore media-type-names
dotnet restore media-type-names-2
dotnet restore middleware\middleware-0
dotnet restore middleware\middleware-1
dotnet restore middleware\middleware-10
dotnet restore middleware\middleware-11
dotnet restore middleware\middleware-12
dotnet restore middleware\middleware-2
dotnet restore middleware\middleware-3
dotnet restore middleware\middleware-4
dotnet restore middleware\middleware-5
dotnet restore middleware\middleware-6
dotnet restore middleware\middleware-7
dotnet restore middleware\middleware-8
dotnet restore middleware\middleware-9
dotnet restore mvc\api-problem-details
dotnet restore mvc\api-problem-details-2
dotnet restore mvc\api-versioning
dotnet restore mvc\hello-world
dotnet restore mvc\jwt
dotnet restore mvc\localization\mvc-localization-1
dotnet restore mvc\localization\mvc-localization-2
dotnet restore mvc\localization\mvc-localization-3
dotnet restore mvc\localization\mvc-localization-4
dotnet restore mvc\localization\mvc-localization-5
dotnet restore mvc\localization\mvc-localization-6
dotnet restore mvc\localization\mvc-localization-7\src\ProjectWithResources
dotnet restore mvc\localization\mvc-localization-7\src\Web
dotnet restore mvc\localization\mvc-localization-8
dotnet restore mvc\localization\mvc-localization-9
dotnet restore mvc\model-binding-from-query
dotnet restore mvc\model-binding-from-route
dotnet restore mvc\mvc-output-xml
dotnet restore mvc\nswag
dotnet restore mvc\nswag-2
dotnet restore mvc\output-formatter-syndication
dotnet restore mvc\razor-class-library\razor-class-library-1\src\RazorClassLibrary1
dotnet restore mvc\razor-class-library\razor-class-library-1\src\RazorClassLibrary2
dotnet restore mvc\razor-class-library\razor-class-library-1\src\WebApplication
dotnet restore mvc\razor-class-library\razor-class-library-with-controllers\src\RazorClassLibrary1
dotnet restore mvc\razor-class-library\razor-class-library-with-controllers\src\WebApplication
dotnet restore mvc\razor-class-library\razor-class-library-with-static-files\src\RazorClassLibraries.Mvc.Core
dotnet restore mvc\razor-class-library\razor-class-library-with-static-files\src\RazorClassLibrary1
dotnet restore mvc\razor-class-library\razor-class-library-with-static-files\src\RazorClassLibrary2
dotnet restore mvc\razor-class-library\razor-class-library-with-static-files\src\WebApplication
dotnet restore mvc\result-filestream
dotnet restore mvc\result-physicalfile
dotnet restore mvc\routing\routing-1
dotnet restore mvc\routing\routing-2
dotnet restore mvc\routing\routing-3
dotnet restore mvc\routing\routing-4
dotnet restore mvc\routing\routing-5
dotnet restore mvc\routing\routing-6
dotnet restore mvc\routing\routing-7
dotnet restore mvc\routing\routing-8
dotnet restore mvc\routing\routing-9
dotnet restore mvc\tag-helper\tag-helper-1
dotnet restore mvc\tag-helper\tag-helper-2
dotnet restore mvc\tag-helper\tag-helper-3
dotnet restore mvc\tag-helper\tag-helper-4
dotnet restore mvc\tag-helper\tag-helper-5
dotnet restore mvc\tag-helper\tag-helper-img
dotnet restore mvc\tag-helper\tag-helper-link
dotnet restore mvc\utf8json-formatter
dotnet restore mvc\view-component\view-component-1
dotnet restore mvc\view-component\view-component-2
dotnet restore mvc\view-component\view-component-3
dotnet restore mvc\view-component\view-component-4
dotnet restore newtonsoft-json
dotnet restore orchard-core\multi-tenant\Host
dotnet restore orchard-core\routing\ForumModule
dotnet restore orchard-core\routing\Host
dotnet restore orchard-core\routing\TicketModule
dotnet restore orchard-core\routing-2\ForumModule
dotnet restore orchard-core\routing-2\Host
dotnet restore orchard-core\routing-2\TicketModule
dotnet restore orchard-core\static-files\ForumModule
dotnet restore orchard-core\static-files\Host
dotnet restore password-hasher
dotnet restore razor-pages\custom-html-generator
dotnet restore razor-pages\hello-world
dotnet restore razor-pages\razor\razor-1
dotnet restore razor-pages\razor\razor-2
dotnet restore razor-pages\razor-pages-basic
dotnet restore razor-pages\razor-pages-mvc
dotnet restore razor-pages\routing
dotnet restore razor-pages\routing-2
dotnet restore request\anti-forgery
dotnet restore request\cookies-1
dotnet restore request\cookies-2
dotnet restore request\form-upload-file
dotnet restore request\form-values
dotnet restore request\query-string-1
dotnet restore request\query-string-2
dotnet restore request\query-string-3
dotnet restore request\request-headers
dotnet restore request\request-headers-names
dotnet restore request\request-headers-typed
dotnet restore request\request-verb
dotnet restore response\compression-response
dotnet restore response\response-buffering
dotnet restore response\response-header
dotnet restore response\trailing-headers
dotnet restore rewrite\rewrite-1
dotnet restore rewrite\rewrite-2
dotnet restore rewrite\rewrite-3
dotnet restore rewrite\rewrite-4
dotnet restore rewrite\rewrite-5
dotnet restore rewrite\rewrite-6
dotnet restore security\authentication-with-identity\src
dotnet restore signalr\signalr-1\Client
dotnet restore signalr\signalr-1\Server
dotnet restore sse
dotnet restore startup\env-development
dotnet restore startup\no-startup
dotnet restore startup\startup-basic
dotnet restore startup\startup-basic-multiple
dotnet restore startup\startup-basic-multiple-environment
dotnet restore startup\startup-basic-multiple-urls
dotnet restore startup\startup-capture-errors
dotnet restore startup\startup-custom-name
dotnet restore startup\startup-istartupfilter
dotnet restore startup\startup-multiple-configure-environment
dotnet restore startup\startup-multiple-configure-environment-services
dotnet restore startup\suppress-status-messages
dotnet restore syndications\syndication-1
dotnet restore syndications\syndication-2
dotnet restore syndications\syndication-3
dotnet restore uri-helper\uri-helper-build-absolute
dotnet restore uri-helper\uri-helper-from-absolute
dotnet restore uri-helper\uri-helper-get-display-url
dotnet restore uri-helper\uri-helper-get-encoded-path-and-query
dotnet restore uri-helper\uri-helper-get-encoded-url
dotnet restore version
dotnet restore web-sockets\web-sockets-1
dotnet restore web-sockets\web-sockets-2
dotnet restore web-sockets\web-sockets-3
dotnet restore web-sockets\web-sockets-4
dotnet restore web-sockets\web-sockets-5
dotnet restore web-utilities\web-utilities-query-helpers
dotnet restore web-utilities\web-utilities-query-helpers-2
dotnet restore web-utilities\web-utilities-reason-phrases
