dotnet build authentication-1
dotnet build authentication-2
dotnet build authentication-3
dotnet build ComponentEighteen
dotnet build ComponentNineteen
dotnet build ComponentTwenty
dotnet build ComponentTwentyOne
dotnet build ComponentTwentyTwo
dotnet build endpoint-filter-1
dotnet build endpoint-filter-2
dotnet build endpoint-filter-3
dotnet build endpoint-filter-4
dotnet build grpc-13
dotnet build grpc-14
dotnet build grpc-15
dotnet build grpc-16
dotnet build grpc-17
dotnet build iform-file
dotnet build iform-file-collection
dotnet build json-23
dotnet build json-24
dotnet build json-25
dotnet build map-group-1
dotnet build map-group-2
dotnet build map-group-3
dotnet build mvc-infer-dependency-from-action
dotnet build open-api-1
dotnet build open-api-2
dotnet build output-cache-1
dotnet build output-cache-2
dotnet build output-cache-3
dotnet build output-cache-4
dotnet build output-cache-5
dotnet build output-cache-6
dotnet build output-cache-7
dotnet build output-cache-8
dotnet build problem-details
dotnet build problem-details-2
dotnet build problem-details-3
dotnet build typed-results-1
