dotnet build hello-world

dotnet build json\json
dotnet build json\json-2
dotnet build json\json-3
dotnet build json\json-4
dotnet build json\json-5
dotnet build json\json-6
dotnet build json\json-7
dotnet build json\json-8
dotnet build json\json-9
dotnet build json\json-10
dotnet build json\json-11

dotnet build blazor\Component
dotnet build blazor\ComponentEight
dotnet build blazor\ComponentEleven
dotnet build blazor\ComponentFifteen
dotnet build blazor\ComponentFive
dotnet build blazor\ComponentFour
dotnet build blazor\ComponentFourteen
dotnet build blazor\ComponentNine
dotnet build blazor\ComponentSeven
dotnet build blazor\ComponentSix
dotnet build blazor\ComponentTen
dotnet build blazor\ComponentThirteen
dotnet build blazor\ComponentThree
dotnet build blazor\ComponentTwelve
dotnet build blazor\ComponentTwo
dotnet build blazor\DataBinding
dotnet build blazor\DataBindingTwo
dotnet build blazor\HelloWorld