dotnet build anti-forgery-1
dotnet build anti-forgery-2
dotnet build anti-forgery-3
dotnet build endpoint-filter-1
dotnet build endpoint-filter-2
dotnet build endpoint-filter-3
dotnet build endpoint-filter-4
dotnet build hello-world
dotnet build iform-file
dotnet build iform-file-collection
dotnet build link-generator-path-by-route-name
dotnet build map
dotnet build map-2
dotnet build map-3
dotnet build map-4
dotnet build map-5
dotnet build map-6
dotnet build map-group-1
dotnet build map-group-2
dotnet build map-group-3
dotnet build map-methods
dotnet build map-post
dotnet build map-post-2
dotnet build minimal-api-form-model-binding
dotnet build open-api-1
dotnet build open-api-2
dotnet build parameter-binding-custom-bind-async
dotnet build parameter-binding-custom-try-parse
dotnet build parameter-binding-header-explicit
dotnet build parameter-binding-json-explicit
dotnet build parameter-binding-json-implicit
dotnet build parameter-binding-query-string-explicit
dotnet build parameter-binding-query-string-implicit
dotnet build parameter-binding-route-explicit
dotnet build parameter-binding-route-implicit
dotnet build parameter-binding-special-types
dotnet build route-constraints-decimal
dotnet build route-constraints-int
dotnet build typed-results-1