dotnet build QuickGridOne
dotnet build RazorComponentFive
dotnet build RazorComponentFour
dotnet build RazorComponentOne
dotnet build RazorComponentSix
dotnet build RazorComponentThree
dotnet build RazorComponentTwo
dotnet build request-timeout
dotnet build request-timeout-2
dotnet build request-timeout-3
dotnet build map-short-circuit
dotnet build slim-builder