dotnet build ComponentTwentyFive
dotnet build ComponentTwentyFour
dotnet build ComponentTwentySix
dotnet build ComponentTwentyThree
dotnet build empty-builder
dotnet build keyed-service
dotnet build keyed-service-2
dotnet build map-short-circuit
dotnet build minimal-api-form-model-binding
dotnet build QuickGridOne
dotnet build RazorComponentEight
dotnet build RazorComponentEleven
dotnet build RazorComponentFive
dotnet build RazorComponentFour
dotnet build RazorComponentNine
dotnet build RazorComponentOne
dotnet build RazorComponentSeven
dotnet build RazorComponentSix
dotnet build RazorComponentTen
dotnet build RazorComponentThree
dotnet build RazorComponentTwo
dotnet build RazorFormHandlingFive
dotnet build RazorFormHandlingFour
dotnet build RazorFormHandlingOne
dotnet build RazorFormHandlingThree
dotnet build RazorFormHandlingTwo
dotnet build RazorMixMatchFour
dotnet build RazorMixMatchOne
dotnet build RazorMixMatchThree
dotnet build RazorMixMatchTwo
dotnet build request-timeout
dotnet build request-timeout-2
dotnet build request-timeout-3
dotnet build slim-builder