dotnet build grpc/client
dotnet build grpc/server
dotnet build grpc-2/client
dotnet build grpc-2/server
dotnet build hello-world-with-reload
dotnet build hosting
dotnet build json
dotnet build json-2
dotnet build json-3
dotnet build json-4
dotnet build json-5
dotnet build json-6
dotnet build new-routing
dotnet build new-routing-2
dotnet build new-routing-3
dotnet build new-routing-4
dotnet build new-routing-5
dotnet build new-routing-6
dotnet build new-routing-7
dotnet build new-routing-8
dotnet build new-routing-9
dotnet build new-routing-10
dotnet build new-routing-11
dotnet build new-routing-12
dotnet build new-routing-13
dotnet build new-routing-14
dotnet build new-routing-15
dotnet build new-routing-16
dotnet build new-routing-17
dotnet build new-routing-18
dotnet build new-routing-19
dotnet build new-routing-20
dotnet build new-routing-21
dotnet build new-routing-22
dotnet build new-routing-23
dotnet build new-routing-24
dotnet build new-routing-25
dotnet build new-routing-26
dotnet build new-routing-27
dotnet build new-routing-28
dotnet build new-routing-29
dotnet build new-routing-30
dotnet build newtonsoft-json
dotnet build version