dotnet build endpoint-routing
dotnet build endpoint-routing-2
dotnet build endpoint-routing-3
dotnet build endpoint-routing-4
dotnet build endpoint-routing-5
dotnet build endpoint-routing-6
dotnet build health-check
dotnet build health-check-2
dotnet build health-check-3
dotnet build health-check-4
dotnet build health-check-5
dotnet build health-check-6
dotnet build new-redis-caching-package
dotnet build parameter-transformer