dotnet build Component
dotnet build ComponentEight
dotnet build ComponentFive
dotnet build ComponentFour
dotnet build ComponentNine
dotnet build ComponentSeven
dotnet build ComponentSix
dotnet build ComponentTen
dotnet build ComponentThree
dotnet build ComponentTwo
dotnet build DataBinding
dotnet build DataBindingTwo
dotnet build hello-world