dotnet build api-problem-details
dotnet build api-problem-details\src
dotnet build api-problem-details\api-problem-details.csproj
dotnet build api-problem-details-2
dotnet build api-versioning
dotnet build hello-world
dotnet build jwt
dotnet build model-binding-from-query
dotnet build model-binding-from-route
dotnet build mvc-localization
dotnet build mvc-localization-2
dotnet build mvc-localization-3
dotnet build mvc-localization-4
dotnet build mvc-localization-5
dotnet build mvc-localization-6
dotnet build mvc-localization-7
dotnet build mvc-output-xml
dotnet build nswag
dotnet build nswag-2
dotnet build output-formatter-syndication
dotnet build razor-class-library
dotnet build razor-class-library-with-controllers
dotnet build razor-class-library-with-static-files
dotnet build razor-pages-basic
dotnet build razor-pages-mvc
dotnet build routing-1
dotnet build routing-2
dotnet build routing-3
dotnet build routing-4
dotnet build routing-5
dotnet build routing-6
dotnet build routing-7
dotnet build routing-8
dotnet build routing-9
dotnet build routing-10
dotnet build routing-table
dotnet build tag-helper
dotnet build tag-helper-2
dotnet build tag-helper-3
dotnet build tag-helper-4
dotnet build tag-helper-5
dotnet build tag-helper-img
dotnet build tag-helper-link
dotnet build utf8json-formatter
dotnet build view-component
dotnet build view-component-2
dotnet build view-component-3
dotnet build view-component-4