dotnet build api
dotnet build api-problem-details
dotnet build api-problem-details-2
dotnet build api-versioning
dotnet build hello-world
dotnet build jwt
dotnet build localization\mvc-localization-1
dotnet build localization\mvc-localization-2
dotnet build localization\mvc-localization-3
dotnet build localization\mvc-localization-4
dotnet build localization\mvc-localization-5
dotnet build localization\mvc-localization-6
dotnet build localization\mvc-localization-7
dotnet build localization\mvc-localization-8
dotnet build localization\mvc-localization-9
dotnet build localization\mvc-localization-10
dotnet build model-binding-from-query
dotnet build model-binding-from-route
dotnet build mvc-infer-dependency-from-action
dotnet build mvc-output-xml
dotnet build newtonsoft-json
dotnet build nswag
dotnet build nswag-2
dotnet build output-formatter-syndication
dotnet build razor-class-library\razor-class-library-1
dotnet build razor-class-library\razor-class-library-with-controllers
dotnet build razor-class-library\razor-class-library-with-static-files
dotnet build result-filestream
dotnet build result-json
dotnet build result-physicalfile
dotnet build routing\routing-1
dotnet build routing\routing-2
dotnet build routing\routing-3
dotnet build routing\routing-4
dotnet build routing\routing-5
dotnet build routing\routing-6
dotnet build routing\routing-7
dotnet build routing\routing-8
dotnet build routing\routing-9
dotnet build tag-helper\tag-helper-1
dotnet build tag-helper\tag-helper-2
dotnet build tag-helper\tag-helper-3
dotnet build tag-helper\tag-helper-4
dotnet build tag-helper\tag-helper-5
dotnet build tag-helper\tag-helper-img
dotnet build tag-helper\tag-helper-link
dotnet build view-component\view-component-1
dotnet build view-component\view-component-2
dotnet build view-component\view-component-3
dotnet build view-component\view-component-4