var app = WebApplication.Create();
app.MapGet("/", () => Results.Content("""
    <!DOCTYPE html>
    <html>
        <head>
            <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/@picocss/pico@2/css/pico.min.css">
        </head>
        <body class="container">
            <h1>Download a response</h1><button hx-get="/report" hx-swap="download">Download report.txt</button>
            <script src="https://cdn.jsdelivr.net/npm/htmx.org@4.0.0/dist/htmx.min.js"></script>
            <script src="https://cdn.jsdelivr.net/npm/htmx.org@4.0.0/dist/ext/hx-download.js"></script>
        </body>
        </html>
    """, "text/html"));

app.MapGet("/report", () => Results.File("Generated by htmx 4\n"u8.ToArray(), "text/plain", "report.txt"));
app.Run();
