dotnet build anti-forgery
dotnet build features-session-redis
dotnet build features-session-redis-2
dotnet build hello-world-startup-all-package
dotnet build iconfiguration
dotnet build ihosted-service
dotnet build logging
dotnet build logging-with-filter
dotnet build razor-pages-basic
dotnet build razor-pages-mvc
dotnet build use-router
dotnet build use-router-2