<Project Sdk="Microsoft.NET.Sdk.Web">
  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <Nullable>enable</Nullable>
    <ImplicitUsings>true</ImplicitUsings>
  </PropertyGroup>
  <ItemGroup>
    <PackageReference Include="Scriban" Version="7.2.6" />
    <PackageReference Include="Markdig" Version="1.3.2" />
    <PackageReference Include="LiteDB" Version="5.0.21" />
    <PackageReference Include="HtmlBuilders" Version="8.1.0" />
    <PackageReference Include="HtmlSanitizer" Version="9.2.995" />
    <PackageReference Include="FluentValidation.AspNetCore" Version="11.3.1" />
  </ItemGroup>
</Project>

