dotnet build hello-world\client\
dotnet build hello-world\silo\
dotnet build hello-world-2\client
dotnet build hello-world-2\silo
dotnet build hello-world-3
dotnet build hello-world-4
dotnet build http-client
dotnet build reminder
dotnet build rss-reader
dotnet build rss-reader-2
dotnet build rss-reader-3
dotnet build rss-reader-4
dotnet build rss-reader-5
dotnet build rss-reader-6
dotnet build timer