dotnet build Component
dotnet build ComponentEight
dotnet build ComponentEleven
dotnet build ComponentFifteen
dotnet build ComponentFive
dotnet build ComponentFour
dotnet build ComponentFourteen
dotnet build ComponentNine
dotnet build ComponentSeven
dotnet build ComponentSeventeen
dotnet build ComponentSix
dotnet build ComponentSixteen
dotnet build ComponentTen
dotnet build ComponentThirteen
dotnet build ComponentThree
dotnet build ComponentTwelve
dotnet build ComponentTwo
dotnet build DataBinding
dotnet build DataBindingTwo
dotnet build HelloWorld
dotnet build RadioButton
dotnet build RenderFragment