dotnet build css-isolation
dotnet build hello-world
dotnet build map
dotnet build map-2
dotnet build map-3
dotnet build map-4
dotnet build map-methods
dotnet build map-post
dotnet build map-post-2
dotnet build web-application
dotnet build web-application-2
dotnet build web-application-3
dotnet build web-application-4
dotnet build web-application-5
dotnet build web-application-6
dotnet build web-application-7
dotnet build web-application-8
dotnet build web-application-9
dotnet build web-application-10
dotnet build web-application-11
dotnet build web-application-12
dotnet build web-application-options
dotnet build web-application-options-2
dotnet build web-application-builder
dotnet build web-application-builder-2
dotnet build web-application-builder-3
dotnet build web-application-builder-4
dotnet build web-application-builder-5
dotnet build yarp/basic-demo/
dotnet build json/json-12
dotnet build json/json-13
dotnet build json/json-14
dotnet build json/json-15
dotnet build json/json-16
dotnet build json/json-17
dotnet build json/json-18
dotnet build json/json-19
dotnet build json/json-20
dotnet build json/json-21
dotnet build json/json-22