dotnet build css-isolation
dotnet build hello-world
dotnet build map
dotnet build map-2
dotnet build map-3
dotnet build map-post
dotnet build map-post-2
dotnet build map-methods
dotnet build web-application
dotnet build web-application-2
dotnet build web-application-3
