<Project Sdk="Microsoft.NET.Sdk.Web">

  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <TieredCompilation>true</TieredCompilation>
      <ImplicitUsings>true</ImplicitUsings>
  </PropertyGroup>

  <ItemGroup>
    <Folder Include="wwwroot\" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="OrchardCore.Application.Targets" Version="3.0.1" />
    <PackageReference Include="OrchardCore.Application.Mvc.Targets" Version="3.0.1" />
  </ItemGroup>

  <ItemGroup>
    <Watch Include="**\*.cshtml" />
  </ItemGroup>

</Project>

