dotnet build grpc/client
dotnet build grpc/server
dotnet build grpc-2/client
dotnet build grpc-2/server
dotnet build grpc-3/client
dotnet build grpc-3/server
dotnet build grpc-4/client
dotnet build grpc-4/server
dotnet build grpc-5/client
dotnet build grpc-5/server
dotnet build grpc-6/client
dotnet build grpc-6/server
dotnet build grpc-7/client
dotnet build grpc-7/server
dotnet build grpc-8/client
dotnet build grpc-8/server
dotnet build grpc-9/client
dotnet build grpc-9/server
dotnet build grpc-10/client
dotnet build grpc-10/server
dotnet build grpc-11/client
dotnet build grpc-11/server
dotnet build grpc-12/client
dotnet build grpc-12/server
