dotnet build generic-host-1
dotnet build generic-host-2
dotnet build generic-host-3
dotnet build generic-host-4
dotnet build generic-host-5
dotnet build generic-host-configure-app
dotnet build generic-host-configure-host
dotnet build generic-host-configure-logging
dotnet build generic-host-environment
dotnet build generic-host-ihostapplicationlifetime